### ISSUE TITLE
Spatial indexing of GeoAgents

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#104]
**What's the problem this feature will solve?**

Mesa-Geo uses RTree for spatial indexing of GeoAgents. When such indexing is not necessary (e.g., no neighborhood queries are needed), it could be a performance bottleneck, especially if there's a huge number of GeoAgents. See https://github.com/wang-boyu/agents-and-networks-in-python/pull/2.

On the other hand, when indexing is actually needed, it happens only when adding agents: https://github.com/projectmesa/mesa-geo/blob/a12f73570c0cf56e94c36675ec0686083882c792/mesa_geo/geospace.py#L292-L308

Whenever agents move and need re-index, users need to manually call `GeoSpace._recreate_rtree()`. For example: https://github.com/projectmesa/mesa-geo/blob/a12f73570c0cf56e94c36675ec0686083882c792/examples/geo_sir/model.py#L109

**Describe the solution you'd like**

- Do not perform spatial indexing when it is not needed.
- When spatial indexing is needed, automatically keep track of agents' movements and re-index accordingly.

**Comment by mrceresa** [comment]
Thanks for opening he issue here!

Maybe we could add an additional layer in GeoSpace specifically for fast moving objects? 

As of know there is the AgentLayer which index everything with rtree and then the StaticLayers with rasters, images and geodataframes

https://github.com/projectmesa/mesa-geo/blob/a3f01ad47a454246c2da05d0d6c7ccc27bcd963b/mesa_geo/geospace.py#L84

Maybe I could add the fast agents as a vector layer and keep track of the movements there

I could try to create a small PR with this change if you think it is interesting

**Comment by wang-boyu** [comment]
Sounds good! A PR would be great - appreciate your time and effort on this!

Just a note on visualization that might be related - `MapVisualization.py` renders `layers` and `agents` separately in different ways: https://github.com/projectmesa/mesa-geo/blob/a3f01ad47a454246c2da05d0d6c7ccc27bcd963b/mesa_geo/visualization/modules/MapVisualization.py#L76-L80

If you have any questions regarding creating a PR, please feel free to ask. We also have a [contributors guide](https://github.com/projectmesa/mesa-geo/blob/main/CONTRIBUTING.md) for your reference.

**Comment by mrceresa** [comment]
Sure! and thanks for the heads-up on the layer rendering, this is indeed important to consider.

I'll look at the contrib guide and post something here as soon as possible

**Comment by wang-boyu** [comment]
Implemented in https://github.com/projectmesa/mesa-geo/pull/179. Closing.
