### ISSUE TITLE
Missing ModularVisualization in rainfall example?

### ISSUE THREAD

**Issue by mrceresa** [projectmesa/mesa-geo#105]
**Describe the bug**
Cloned the repo and run the coverage tests:

```
$ pytest --cov=mesa_geo tests/
>   from mesa_geo.visualization.ModularVisualization import ModularServer
E   ModuleNotFoundError: No module named 'mesa_geo.visualization.ModularVisualization'
examples/rainfall/rainfall/server.py:5: ModuleNotFoundError
```

**Expected behavior**
Running the test suite should not give any errors

Indeed I don't see the module anymore in the visualization folder of mesa-geo

Maybe I'm getting confused from https://github.com/projectmesa/mesa-geo/issues/76

Or I simply messed up the dev installation?

**Comment by wang-boyu** [comment]
Hmm this is interesting. But I do not have this issue on my side.

Could you try to use a clean virtual environment from scratch, and install dependencies and Mesa-Geo via `pip install -e ".[dev]"`?

**Comment by mrceresa** [comment]
Hey, thanks for the quick answer. I'm testing it now on my home pc (ubuntu)

This is what I tried;
~~~
git clone https://github.com/projectmesa/mesa-geo.git
cd mesa-geo/
mamba create -n testmg python
mamba activate testmg
pip install -e ".[dev]"
pytest --cov=mesa_geo tests/
[...]
    import mesa
>   from mesa_geo.visualization.ModularVisualization import ModularServer
E   ModuleNotFoundError: No module named 'mesa_geo.visualization.ModularVisualization'

examples/geo_schelling/server.py:2: ModuleNotFoundError
~~~
Here the full output of the pytest errors and the mamba package list:
[pytest_errors.txt](https://github.com/projectmesa/mesa-geo/files/9658670/pytest_errors.txt)
[mamba_list.txt](https://github.com/projectmesa/mesa-geo/files/9658672/mamba_list.txt)

Thanks for your help!

**Comment by wang-boyu** [comment]
I see. Looks like Mesa-Geo is not properly installed for some reason.

We do not have a `mesa_geo.visualization.ModularVisualization` module in our code base; it is actually copied over from `Mesa` during setup. See: https://github.com/projectmesa/mesa-geo/blob/a3f01ad47a454246c2da05d0d6c7ccc27bcd963b/setup.py#L43

How about `pip install -e .` or install from PyPI directly, i.e., `pip install mesa-geo`? I am not very sure why this is happening.

**Comment by mrceresa** [comment]
okay so this is interesting: it seems that (at least on my machine) there is a subtle difference in the way setuptools treats command classes between install and install_editable with pip.

I start from a fresh clone (so the ModularVisualization.py file is not there) then:

1) If I install with `pip install .` the **build** command is properly called and the file is copied. Everything work and this is the expected behaviour
2) This is also the case, if I manually run `python setup.py install/develop `
3) Now, if I install with `pip install -e .` the **develop** command is **not** called and I **don't get** the visualization/ModularVisualization.py. Tests then obviously fail.
4) This is also the case for `pip install -e .[dev]`

So the question is, why --editable is not calling neither the build nor the develop subcommands?

Actually `pip install .` calls the custom build command, as we can see from this log ("INSIDE BUILD") is my debug text

~~~
Building wheels for collected packages: Mesa-Geo
  Created temporary directory: /tmp/pip-wheel-uy4v8atq
  Destination directory: /tmp/pip-wheel-uy4v8atq
  Running command Building wheel for Mesa-Geo (pyproject.toml)
  /tmp/pip-build-env-6f4grtxt/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running bdist_wheel
  running build
  INSIDE BUILD
  Downloading the leaflet.js dependency from the internet...
  Downloading the leaflet.css dependency from the internet...
  running build_py
~~~


On the other side, `pip install --editable . ` calls **editable_wheel** and not **develop**

~~~
Building wheels for collected packages: Mesa-Geo
  Created temporary directory: /tmp/pip-wheel-0upylsq5
  Destination directory: /tmp/pip-wheel-0upylsq5
  Running command Building editable for Mesa-Geo (pyproject.toml)
  /tmp/pip-build-env-atgt3u8t/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running editable_wheel
  creating /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info
  writing /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/requires.txt
  writing top-level names to /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/top_level.txt
  writing manifest file '/tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo.egg-info/SOURCES.txt'
  creating '/tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo-0.3.0.dist-info'
  creating /tmp/pip-wheel-0upylsq5/tmpjw6p7snr/Mesa_Geo-0.3.0.dist-info/WHEEL
  /tmp/pip-build-env-atgt3u8t/overlay/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build_py
  running egg_info
~~~

Thus no file is copied...

**Comment by mrceresa** [comment]
As a proof, if I change the setup.py accordingly:

~~~
--- a/setup.py
+++ b/setup.py
@@ -12,6 +12,7 @@ from distutils.command.build import build
 
 from setuptools import setup
 from setuptools.command.develop import develop
+from setuptools.command.editable_wheel import editable_wheel
 
 
 def get_version_from_package() -> str:
@@ -22,10 +23,22 @@ def get_version_from_package() -> str:
     return version
 
 
+class EdiWheelCommand(editable_wheel):
+    """Installation for development mode."""
+
+    def run(self):
+        print("INSIDE EDIWHEEL")
+        get_mesa_viz_files()
+        get_frontend_dep()
+        editable_wheel.run(self)
 
 if __name__ == "__main__":
+
     setup(
         name="Mesa-Geo",
         version=get_version_from_package(),
         cmdclass={
+            "editable_wheel": EdiWheelCommand,
             "develop": DevelopCommand,
:


~~~

~~~
Building wheels for collected packages: Mesa-Geo
  Created temporary directory: /tmp/pip-wheel-556vurov
  Destination directory: /tmp/pip-wheel-556vurov
  Running command Building editable for Mesa-Geo (pyproject.toml)
  /tmp/pip-build-env-ysf_0t7s/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running editable_wheel
  INSIDE EDIWHEEL
~~~

And the ModularVisualization.py file is present again!

**Comment by rht** [comment]
We should replace the `get_mesa_viz_files` mechanism. This pattern seems to be non-standard in Python package setups.

**Comment by mrceresa** [comment]
Yes, if you can confirm this, we could:

* Leave it like this (nobody a part me seem to have had the same problem)
* Extend the build_py command instead of build and develop as this seems to be always called 
* Maybe consider using the recent [sub_command](https://github.com/pypa/setuptools/issues/2591) extension from setuptools to add additional build steps

And additional question: is there any reason why build is imported from distutils and the rest from setuptools?

**Comment by wang-boyu** [comment]
@mrceresa If `get_mesa_viz_files()` is not called as expected, how about `get_frontend_dep()`? Do the Leaflet files (js and css) get downloaded?

If not then we may still need to address this issue for the Leaflet dependency.

**Comment by zlfdodo** [comment]
I got the same problem when I installed mesa-geo from git. I reinstall this package by using 'pip install mesa-geo' and it works.

**Comment by wang-boyu** [comment]
@zlfdodo Sorry about that. Could you share which operating system and python version were used?

**Comment by zlfdodo** [comment]
@wang-boyu Thanks for the prompt reply. I am using Windows system and conda python 3.10.6. The mesa-geo package only works under this python version on my computer. When I use any other python version in Anaconda and run any model/run.py file in the example folder, it will return "ImportError: DLL load failed while importing_version."
