### ISSUE TITLE
Improving `RasterLayer`

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#120]
**What's the problem this feature will solve?**

As mentioned in the docstrings, some methods in `RasterLayer` are copied from `mesa.space.Grid`, including:

    __getitem__
    __iter__
    coord_iter
    iter_neighborhood
    get_neighborhood
    iter_neighbors
    get_neighbors  # copied and renamed to `get_neighboring_cells`
    out_of_bounds  # copied into `RasterBase`
    iter_cell_list_contents
    get_cell_list_contents

Recently `mesa.space.Grid` has received some improvements (refactoring, performance improvements, and so on) but these are not reflected in `RasterLayer`.

**Describe the solution you'd like**

Wait until some pending PRs get merged and copy these changes over, until we figure out a better way to incorporate these changes automatically (like mentioned at https://github.com/projectmesa/mesa-geo/pull/75#discussion_r914452359).

**Comment by rht** [comment]
I haven't been able to find a class name that encompasses those methods, while excluding
```
torus_adj
neighbor_iter
move_agent
place_agent
_place_agent
remove_agent
is_cell_empty
move_to_empty
find_empty
exists_empty_cells
```
What would be the consequence for `RasterLayer` to have those methods? Maybe the `*_agent` methods can be replaced with methods that raise `NotImplementedError`?

**Comment by wang-boyu** [comment]
The main difference between `RasterLayer` and `Grid`are:

1. The `GridContent` in `Grid` is `Cell` in `RasterLayer`. This is fine since `GridContent = Union[Agent, None]` and `Cell` inherits `Agent`.
2. In `Grid` there is `self.grid: list[list[GridContent]]` whereas in `RasterLayer` we have `self.cells: list[list[Cell]]`. This is a bit troublesome because `self.grid` is effectively renamed to `self.cells`.

Another issue is that we do not manipulate agents using `RasterLayer` directly. Instead, adding/updating/removing agents methods are defined at the `GeoSpace` level. It might be confusing if we have these methods also defined within `RasterLayer` and raise `NotImplementedError`.

I couldn't think of any easier ways to get necessary methods from `Grid` while avoiding the rest. Was hoping that changes wouldn't happen very often.

**Comment by wang-boyu** [comment]
Mesa now has an experimental `PropertyLayer` and could be an alternative implementation for our `RasterLayer`: https://github.com/projectmesa/mesa/pull/1898

**Comment by wang-boyu** [comment]
Replaced by https://github.com/projectmesa/mesa-geo/issues/201. Closing this issue now.
