### ISSUE TITLE
Consistency in README tutorial 

### ISSUE THREAD

**Issue by majdal** [projectmesa/mesa-geo#20]
Going through the tutorial in README, there's a small error that that took me a bit of investigating to figure out, so maybe it's worthwhile to correct. I'm happy to create a pull request, but first I'd like to hear from the author/community about what's the best way to correct it. 

The GeoJSON that you provide in the example is in WGS84 (`EPSG:4326`), not in WGS 84 / Pseudo-Mercator (`EPSG:3857`). With the default CRS (3857), the example shows a blank box instead of the map of Arizona.  Setting the CRS explicitly in the `AgentCreator` to 4326 fixes the issue. The image attached should be corrected to look like the following: 

<img width="114" alt="Arizona map at epsg:4326" src="https://user-images.githubusercontent.com/360058/75496422-bea4ee80-59c9-11ea-8651-e986c68b6975.png">

The image currently in the tutorial is the one below, and it's in `epsg:2163`. The difference might create some unnecessary confusion to a beginner. 

<img width="114" alt="Arizona map at epsg:2163" src="https://raw.githubusercontent.com/majdal/mesa-geo/master/output_3_1.svg?sanitize=true">

This also means that the distance calculation (`m.grid.get_neighbors_within_distance(agent, 600000)`) has the wrong distance/units. 

Should we move the reference to explicitly setting the CRS to be just after the model definition?

**Comment by ArcPam** [comment]
This might be why my files are defaulting to the top of the page. Do you know how to fix that issue?

**Comment by majdal** [comment]
@ArcPam I'm not sure I understand your question... More details please

**Comment by ArcPam** [comment]
I was able to fix the issue by projecting all data in 4326 and it fixed the issue.

**Comment by wang-boyu** [comment]
[Introductory tutorial](https://mesa-geo.readthedocs.io/en/stable/tutorials/intro_tutorial.html) has changed to a step-by-step SIR model using Solara visualization in Jupyter notebook. Hence this issue no longer exists. Closing.
