### ISSUE TITLE
ci: merge setup.cfg into pyproject.toml

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#200]
We had two separated files, `setup.cfg` and `pyproject.toml` because some fields were marked as experimental back when they were created: https://github.com/projectmesa/mesa-geo/pull/54#issuecomment-1093635010. Now that Mesa uses only `pyproject.toml`, it would be nice to follow its convention, and making it easier to maintain too.

For example in `pyproject.toml ` we have

https://github.com/projectmesa/mesa-geo/blob/574e3a6c0fd49d6cf6e1cdc5dda72407517c3c47/pyproject.toml#L5

whereas in `setup.cfg ` it is 

https://github.com/projectmesa/mesa-geo/blob/574e3a6c0fd49d6cf6e1cdc5dda72407517c3c47/setup.cfg#L33

something that I forgot to update in https://github.com/projectmesa/mesa-geo/pull/186.

**Comment by EwoutH** [comment]
I think we should also remove the setup.py in that case. I think that's still leading?

**Comment by EwoutH** [comment]
I think this is a good start: [`pyproject-toml`](https://github.com/projectmesa/mesa-geo/tree/pyproject-toml) Only thing I don't know how to handle is the scripts in setup.py. Are those still essential?

Feel free to continue working on that branch.

**Comment by wang-boyu** [comment]
Implemented in https://github.com/projectmesa/mesa-geo/pull/208. Closing.
