### ISSUE TITLE
Update Mesa-geo visualisation based on updated SolaraViz API

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-geo#262]
Since the SolaraViz API was updated, the Mesa-geo API also needs to be updated to match it. See:
- https://github.com/projectmesa/mesa/pull/2447

**Comment by wang-boyu** [comment]
Thanks for noticing this! Do you mean renaming `make_geospace_leaflet` to `make_geospace_component` to be consistent with Mesa? Anything else that I'm missing?

**Comment by wang-boyu** [comment]
Implemented in https://github.com/projectmesa/mesa-geo/pull/270. Closing.
