### ISSUE TITLE
Agent Not Proper Removed With GeoSpace.remove_agent

### ISSUE THREAD

**Issue by MuscularBrain** [projectmesa/mesa-geo#28]
It seems like the dictionary index.agents is not properly updated after remove_agent takes place. This results in issue such that when referencing grid.agents in a model, the removed agent still exists.

**Comment by Corvince** [comment]
Thanks, I can confirm this bug. The index went under several iterations and I seem to have forgotten to update the remove function. This repo clearly needs at least some basic testing.
