### ISSUE TITLE
Exclude some GeoAgents attributes from visualization

### ISSUE THREAD

**Issue by giacrava** [projectmesa/mesa-geo#32]
I already encountered two situations where some GeoAgents' attributes are causing the impossibility of visualizing the model interactively. 1) When they cause the agent to not be JSON serializable (for instance causing reciprocal references of agents or being pandas data structures), which causes an error 2) When they store lots of data, which makes the initialization of the visualization too long.

Is there a way to exclude some attributes of the GeoAgents from the interactive visualization? Thanks!

**Comment by stefaneidelloth** [comment]
I also got an error message that an additional agent property was not serializable. 
A possible workaround might be to implement a custom __geo_interface__ method:

```
    def __geo_interface__(self):
        """
        Override the default __geo_interface__ method of GeoAgent to resolve some serialization issues.

        Return a GeoJSON Feature.

        Removes shape from attributes.
        """
        properties = dict(vars(self))
        properties["model"] = str(self.model)
        shape = properties.pop("shape")

        properties.pop("site")  # <= removes site because it is not serializable 

        shape = transform(self.model.grid.Transformer.transform, shape)

        return {"type": "Feature", "geometry": mapping(shape), "properties": properties}
```

**Comment by wang-boyu** [comment]
In your custom `__geo_interface__` method, what if `properties` is changed into an empty dictionary? That is, to get rid of all attributes:

```
return {"type": "Feature", "geometry": mapping(shape), "properties": properties}
```

into

```
return {"type": "Feature", "geometry": mapping(shape), "properties": {}}
```

Subsequently the useful properties will be set in the [render()](https://github.com/projectmesa/mesa-geo/blob/f5dc628c3674c7faa42c3a4d2053d6cc69f6fa5e/mesa_geo/visualization/MapModule.py#L21) function of `MapModule`. In this way hopefully only the necessary fields are sent to frontend for visualization.
