### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by Harshpanday** [projectmesa/mesa-geo#37]
Hello everyone,
How can I access the attributes of the Geodataframe that I use to add the agents?
In the project, I am working on I want to access the coordinates of each agent and use them. Is there a way I can do that?
I already did "set_attributes = True", but I am confused as to how can I access their attributes.

I will be very grateful if anyone can point me in the right direction.

With kindest regards,
Harsh Panday

**Comment by Corvince** [comment]
Yes you are correct. `agent.shape` is named due to historical reasons, since originally everything was based on shapely shapes. But definitely should be renamed to `agent.geometry`.

**Comment by wang-boyu** [comment]
Thanks for your clarification, it helps a lot. I was always wondering why `agent.shape` was used instead of `agent.geometry`, and whether to just change it back.

I'll send a PR to rename to `agent.geometry`.

**Comment by wang-boyu** [comment]
With https://github.com/projectmesa/mesa-geo/pull/57, `geometry` is no longer renamed to `shape`. As I mentioned in https://github.com/projectmesa/mesa-geo/pull/57#discussion_r850491780, The current behavior is:

1.  If we have the following data:

| | name | geometry |
| :---: | :---: | :---: |
| 0 | Alice | POINT (1.00000 2.00000) |
| 1 | Bob | POINT (2.00000 1.00000) |

then it gets loaded as `agent.name` and `agent.geometry` respectively.

2. If the active geometry of the GeoDataFrame is of other name, then it's also gets loaded as `geometry`. For example:

| | name | home | work |
| :---: | :---: | :---: | :---: |
| 0 | Alice | POINT (1.00000 2.00000) | POINT (3.00000 4.00000) |
| 1 | Bob | POINT (2.00000 1.00000) | POINT (4.00000 5.00000) |

If `home` is the active geometry column, then `gdf.geometry` and `gdf.home` are essentially the same thing. And it'll be loaded as `agent.name`, `agent.geometry`, and `agent.work` respectively.

**Comment by Harshpanday** [comment]
Thank you for the clarification and changes.
