### ISSUE TITLE
JS/CSS dependencies management in mesa-geo

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#52]
**What's the problem this feature will solve?**

Some JS/CSS files and their corresponding python modules are copied over from mesa, and may be incomplete or out-of-date.

This also leads to confusion from users on which frontend files belong to mesa-geo (e.g. https://github.com/projectmesa/mesa-geo/issues/42).

**Describe the solution you'd like**

The solution will depend on how mesa manages the frontend files in the future.

Besides, there have been some fixes and some ongoing efforts to improve the frontend elements in mesa, such as

- https://github.com/projectmesa/mesa/issues/1216
- https://github.com/projectmesa/mesa/issues/1232
- https://github.com/projectmesa/mesa/issues/1233
- https://github.com/projectmesa/mesa/issues/1235
- https://github.com/projectmesa/mesa/issues/1249

These fixes and improvements should be automatically applied to mesa-geo.

Lastly, the solution should be flexible in that, extensions and modifications to existing frontend elements can be done easily in mesa-geo.

**Additional context**

- https://github.com/projectmesa/mesa/issues/1195

**Comment by rht** [comment]
I ended up doing https://github.com/projectmesa/mesa/pull/1220 instead of using Fanstatic because its JS packages are outdated. Follow up: https://github.com/projectmesa/mesa/pull/1236.

**Comment by wang-boyu** [comment]
Thanks for the update!

**Comment by wang-boyu** [comment]
This issue is partly addressed in https://github.com/projectmesa/mesa-geo/pull/54, with the exception of `visualization/templates/modular_template.html` which still needs to be manually updated to be in sync with Mesa. 

To do:

- [ ] Have `visualization/templates/modular_template.html` copied from Mesa during setup, as soon as https://github.com/projectmesa/mesa/issues/1267 is implemented.
