### ISSUE TITLE
Other map visualization 

### ISSUE THREAD

**Issue by eecoo** [projectmesa/mesa-geo#66]
I would be nice to have another map visualization like google maps, i know its paid but you would just have to get an activation key

**Comment by wang-boyu** [comment]
Publicly available map tiles are supported now, as summarized in https://github.com/projectmesa/mesa-geo/issues/48#issuecomment-1342886964.

If map providers need access keys, we can specify them when defining `RasterWebTile`:

```python
map_tile = mg.RasterWebTile(
             url="https://PROVIDER_URL.png?key={key}",
             options={
                 "attribution": PROVIDER_ATTRIBUTION,
                 "key": API_KEY,
             },
         )
map_element = mg.visualization.MapModule(..., tiles=map_tile, ...)
```

or use those from [xyzservices](https://github.com/geopandas/xyzservices) and provide them like mentioned in their [docs](https://xyzservices.readthedocs.io/en/stable/registration.html).

**However this is not yet tested** - I am not sure whether Leaflet.js will work with such configurations automatically. Perhaps some more work in `MapModule.js` is required when passing these configurations to Leaflet.js.

I will register some map services and test this later.

**Comment by wang-boyu** [comment]
Tested with Mapbox and it appears to be working. I can either use

```python
import mesa_geo as mg

mg.RasterWebTile(
    url="https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?access_token={access_token}",
    options={
        "access_token": "my-private-ACCESS_TOKEN",
        "attribution": '&copy; <a href="https://www.mapbox.com/about/maps/" target="_blank">Mapbox</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors <a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a>',
    },
)
```

or

```python
import xyzservices.providers as xyz

xyz.MapBox(id="<insert map_ID here>", accessToken="my-private-ACCESS_TOKEN")
```

Note that `access_token` can have different names depending on the provider, e.g., `api_key` or `key`.

I will update the docstrings accordingly. Closing this as completed.
