### ISSUE TITLE
How can I get step count?

### ISSUE THREAD

**Issue by Harshpanday** [projectmesa/mesa-geo#68]
So, I am saving the results of each step in a CSV file. I want to save the step number too. How can I get the step count?
I tried counting through a variable like ```count=0``` and then ```count+=1```, but that doesn't work properly as it increments the count for each agent (eg I have 4 different types of agents like I have 100 agent 1's 50 agent 2's etc, so the count variable will increment the count 100 times just for agent 1).
On the command line, when I click step I can see a dictionary that has steps inside it. If somehow I can access that, that would work too (I have looked through the root code and I couldn't find it).
Sorry if the question is confusing, please let me know If anyone wants me to explain more.
I will be very grateful for any suggestions.

**Comment by wang-boyu** [comment]
There should be a `steps` property in your model's scheduler, i.e., `model.schedule.steps`.

Alternatively if you prefer to implement this on your own, or do some custom tasks with the steps, perhaps you could try to increment your `count` inside the `model.step()` function, instead of `agent.step()`.

**Comment by rht** [comment]
You can get the step count info from the scheduler, `model.schedule.steps`. You can access this by defining a model-level data collector function.

**Comment by rht** [comment]
Oh, I didn't see that @wang-boyu already answered this.

**Comment by rht** [comment]
@Harshpanday I think we answered your question. Let us know if you encounter any problem. Closing.
