### ISSUE TITLE
No Codecov report for pull request base

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#70]
**Describe the bug**

Whenever a PR is submitted, Codecov Report shows "No coverage uploaded for pull request base".

Example: https://github.com/projectmesa/mesa-geo/pull/69#issuecomment-1148381066

**Expected behavior**

Example: https://github.com/projectmesa/mesa/pull/1355#issuecomment-1148269552

**To Reproduce**

Submit any PR to reproduce.

**Comment by rht** [comment]
https://app.codecov.io/gh/projectmesa/mesa-geo

Probably need to ask codecov.io's tech support about it.

**Comment by wang-boyu** [comment]
Let me see if adding a `.coveragerc` file helps.

I contacted codecov.io but they do not provide support : ( Their reply:

> Thanks for reaching out to Codecov Support. Please note that, with hundreds of thousands of developers using Codecov, we are not able to offer direct email support to our open source / free users at this time.
>
> To that end, we strongly recommend visiting our [Community Board](https://community.codecov.io/) to see if this request has come up before or to create a new post there. Our Support Team reviews the posts on that board regularly to provide best-effort support. 
>
> In case you are on a paid plan and this message was an error, please let us know and we will get back to you shortly.

**Comment by rht** [comment]
Seems to be fixed via the `.coveragerc`! See #72 for the test.
