### ISSUE TITLE
Use ModularServer from Mesa

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#76]
**What's the problem this feature will solve?**

Currently Mesa-Geo users need to use `ModularServer` from `mesa_geo.visualization.ModularVisualization`, instead of `mesa.visualization.ModularVisualization`, which could be confusing and lead to errors.

**Describe the solution you'd like**

Use `ModularServer` directly from `mesa.visualization.ModularVisualization`.

**Additional context**

See comments from https://github.com/projectmesa/mesa/pull/1369

**Comment by rht** [comment]
Closed via #109
