### ISSUE TITLE
Add scale to Leaflet map

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa-geo#96]
**What's the problem this feature will solve?**

This feature will add a scale, which is a common element of a map.

**Describe the solution you'd like**

Use Leaflet's builtin scale control, or similar third-party Leaflet plugins. Scale options can be added into `mesa_geo.visualization.modules.MapModule`.

**Additional context**

- [Scale control in Leaflet.js](https://leafletjs.com/reference.html#control-scale)
- [A better scalebar for leaflet maps](https://github.com/daniellsu/leaflet-betterscale)

**Comment by rht** [comment]
Closed via #123.
